[package]
name = "a7box"
version = "0.1.5"
description = "A7Box - Your Tactical Efficiency Weapon on Desktop"
authors = ["bluvenr"]
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "a7box_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-shell = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-autostart = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
arboard = "3"
screenshots = "0.8"
tiny_http = "0.12"
chrono = "0.4"
uuid = { version = "1", features = ["v4"] }
dirs = "5"
base64 = "0.22"
local-ip-address = "0.6"
sys-locale = "0.3"
open = "5"
# P2P LAN transfer
mdns-sd = "0.11"
sha2 = "0.10"
hostname = "0.4"
rand = "0.8"
tauri-plugin-dialog = "2.7.1"
tauri-plugin-deep-link = "2"
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }
tauri-plugin-fs = "2.5.1"
# Clipboard Manager
rusqlite = { version = "0.31", features = ["bundled"] }
aes-gcm = "0.10"
hkdf = "0.12"
image = { version = "0.25", default-features = false, features = ["png"] }
enigo = "0.2"
regex = "1"
tauri-plugin-device-info = "1"
sysinfo = "0.34"
default-net = "0.22"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"
windows = { version = "0.58", features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_Graphics_Dwm",
  "Win32_Graphics_Gdi",
  "Win32_UI_HiDpi",
  "Win32_Foundation",
  "Win32_UI_Shell",
  "Win32_System_DataExchange",
  "Win32_System_Memory",
  "Win32_System_LibraryLoader",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_System_Threading",
] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

